export default {
  name: 'Demo',
  created: '2022-01-17T14:06:14.367Z',
  videos: [
    {
      kind: 'youtube#video',
      etag: 'J4AKDKUzBKXpKKlRAOJHm1HpCFA',
      id: 'sHdrRWRbK6k',
      snippet: {
        publishedAt: '2022-01-12T12:00:34Z',
        channelId: 'UCht8qITGkBvXKsR1Byln-wA',
        title: 'What If – Jay Someday (No Copyright Music)',
        description:
          "Download free and safe music for content creators (Free Music, No Copyright Music, Royalty-free Music, and Creative Commons) · http://bit.ly/Join-the-family\n\nPlease subscribe! ❤️\nWe upload a new song EVERY day http://bit.ly/32TUZyy\n\n———\n\n⭐ Free Download: https://bit.ly/3EIgcxU\n\n———\n\n⚠️ You’re free to use this song in any of your YouTube videos, but you MUST include the following in your video description (Copy & Paste):\n\n––––––––––––––––––––––––––––––\nWhat If by Jay Someday https://soundcloud.com/jaysomeday\nCreative Commons — Attribution 3.0 Unported — CC BY 3.0\nFree Download / Stream: https://bit.ly/3EIgcxU\nMusic promoted by Audio Library https://youtu.be/sHdrRWRbK6k\n––––––––––––––––––––––––––––––\n\n🎵 Track Info:\n\nTitle: What If by Jay Someday\nGenre and Mood: Ambient + Calm\n\n———\n\n🎧 Available on: \n\nSpotify: https://spoti.fi/3IE7Ud8\niTunes: https://apple.co/3ybT5JL\nDeezer: https://deezer.com/es/track/1359117462\nYouTube: https://youtube.com/watch?v=jMDmwX3RSZM\nSoundCloud: https://soundcloud.com/jaysomeday/what-if-free-download\nYouTube Music: https://music.youtube.com/watch?v=jMDmwX3RSZM\n\n———\n\n😊 Contact the Artist:\n\nJay Someday:\nhttps://jaysomeday.wordpress.com\nhttps://soundcloud.com/jaysomeday\nhttps://deezer.com/us/artist/60517872\nhttps://youtube.com/channel/UC-Tu93w5hiK7NLGvOXvHW9g\nhttps://open.spotify.com/artist/6hPfMVwvSPNMZKvFg9IDIF\nhttps://music.apple.com/us/artist/jay-someday/1454604441\nhttps://facebook.com/jaysomedaymusic\nhttps://instagram.com/jaysomeday\n\n———\n\n✅ About using the music:\n\n- You MUST include the full credits in your video description.\n- You can NOT claim the music as your own.\n- You can NOT sell the music anywhere.\n- You can NOT use the music as background music for your own musical work without the artist's consent.\n- You can NOT use the music without giving any credits in the video description.\n- You can NOT remove or add parts from/to the credits.\n- You can NOT use third-party software to download the video/track, always use our download links\n- You MUST contact the artist if you wish to use the music on any kind of project outside of YouTube.\n\n⚠️ Important:\n\n- If you don't follow these policies, you can get a copyright claim/strike.\n- If you need more information about using music, please get in touch with the artist.\n- This channel is not an official YouTube channel.\n\n———\n\n💚 Listen to our Spotify playlists\n\nEDM: http://spoti.fi/30R0jTw\nLo-Fi: http://spoti.fi/38OptGM\nChill: http://spoti.fi/3rX5gWN\nHappy: https://spoti.fi/2Qjk6JD\n\n———\n\n🔴 Official Releases: http://bit.ly/al-plus\n\nWe have created a new channel where we do an agreement with the artist and our record label to make sure all the music is free and 100% safe. \n\n———\n\n🔀 More free music:\n\nPop Music: http://bit.ly/pop-music-playlist\nHip Hop & Rap Music: http://bit.ly/hip-hop-rap-playlist\nDance & Electronic Music: http://bit.ly/dance-electronic-playlist\n\nMore playlists: http://bit.ly/audiolibrary-playlists\n\n———\n\n❤️ Get in touch with Audio Library:\n\nE-mail: hello@audiolibrary.com.co\nWebsite: https://www.audiolibrary.com.co\nInstagram: http://bit.ly/aI-instagram\nFacebook: http://bit.ly/al-facebook\nSoundCloud: http://bit.ly/al-soundcloud\nTwitter: http://bit.ly/aI-twitter\n\n———\n\n🔥 Send your demo: http://www.audiolibrary.com.co/demo\n\n———\n\nPlease report to (report@audiolibrary.com.co) any issues with this video/song/image, from broken links, copyright claim/strikes to someone using the music without giving credit or selling the music.\n\n———\n\nRead our disclaimer before using the music.\nhttp://bit.ly/2KA71pn\n\n———\n\n#VlogMusic #NoCopyrightMusic #AudioLibrary",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/sHdrRWRbK6k/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/sHdrRWRbK6k/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/sHdrRWRbK6k/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/sHdrRWRbK6k/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/sHdrRWRbK6k/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'Audio Library — Music for content creators',
        tags: [
          'Jay Someday',
          'What If',
          'Jay Someday - What If',
          'Jay Someday music',
          'audio library',
          'free music',
          'vlog',
          'vlog music',
          'no copyright music',
          'background music',
          'royalty free',
          'free music to use',
          'free music download',
          'free vlogging music',
          'free copyright music',
          'vlogger music',
          'vlogging music',
          'vlog no copyright',
          'music for vlog',
          'music for videos',
          'music for youtube videos',
          'download background music',
          'download free music',
          'download music',
          'ambient',
          'calm',
          'cc',
        ],
        categoryId: '10',
        liveBroadcastContent: 'none',
        defaultLanguage: 'en',
        localized: {
          title: 'What If – Jay Someday (No Copyright Music)',
          description:
            "Download free and safe music for content creators (Free Music, No Copyright Music, Royalty-free Music, and Creative Commons) · http://bit.ly/Join-the-family\n\nPlease subscribe! ❤️\nWe upload a new song EVERY day http://bit.ly/32TUZyy\n\n———\n\n⭐ Free Download: https://bit.ly/3EIgcxU\n\n———\n\n⚠️ You’re free to use this song in any of your YouTube videos, but you MUST include the following in your video description (Copy & Paste):\n\n––––––––––––––––––––––––––––––\nWhat If by Jay Someday https://soundcloud.com/jaysomeday\nCreative Commons — Attribution 3.0 Unported — CC BY 3.0\nFree Download / Stream: https://bit.ly/3EIgcxU\nMusic promoted by Audio Library https://youtu.be/sHdrRWRbK6k\n––––––––––––––––––––––––––––––\n\n🎵 Track Info:\n\nTitle: What If by Jay Someday\nGenre and Mood: Ambient + Calm\n\n———\n\n🎧 Available on: \n\nSpotify: https://spoti.fi/3IE7Ud8\niTunes: https://apple.co/3ybT5JL\nDeezer: https://deezer.com/es/track/1359117462\nYouTube: https://youtube.com/watch?v=jMDmwX3RSZM\nSoundCloud: https://soundcloud.com/jaysomeday/what-if-free-download\nYouTube Music: https://music.youtube.com/watch?v=jMDmwX3RSZM\n\n———\n\n😊 Contact the Artist:\n\nJay Someday:\nhttps://jaysomeday.wordpress.com\nhttps://soundcloud.com/jaysomeday\nhttps://deezer.com/us/artist/60517872\nhttps://youtube.com/channel/UC-Tu93w5hiK7NLGvOXvHW9g\nhttps://open.spotify.com/artist/6hPfMVwvSPNMZKvFg9IDIF\nhttps://music.apple.com/us/artist/jay-someday/1454604441\nhttps://facebook.com/jaysomedaymusic\nhttps://instagram.com/jaysomeday\n\n———\n\n✅ About using the music:\n\n- You MUST include the full credits in your video description.\n- You can NOT claim the music as your own.\n- You can NOT sell the music anywhere.\n- You can NOT use the music as background music for your own musical work without the artist's consent.\n- You can NOT use the music without giving any credits in the video description.\n- You can NOT remove or add parts from/to the credits.\n- You can NOT use third-party software to download the video/track, always use our download links\n- You MUST contact the artist if you wish to use the music on any kind of project outside of YouTube.\n\n⚠️ Important:\n\n- If you don't follow these policies, you can get a copyright claim/strike.\n- If you need more information about using music, please get in touch with the artist.\n- This channel is not an official YouTube channel.\n\n———\n\n💚 Listen to our Spotify playlists\n\nEDM: http://spoti.fi/30R0jTw\nLo-Fi: http://spoti.fi/38OptGM\nChill: http://spoti.fi/3rX5gWN\nHappy: https://spoti.fi/2Qjk6JD\n\n———\n\n🔴 Official Releases: http://bit.ly/al-plus\n\nWe have created a new channel where we do an agreement with the artist and our record label to make sure all the music is free and 100% safe. \n\n———\n\n🔀 More free music:\n\nPop Music: http://bit.ly/pop-music-playlist\nHip Hop & Rap Music: http://bit.ly/hip-hop-rap-playlist\nDance & Electronic Music: http://bit.ly/dance-electronic-playlist\n\nMore playlists: http://bit.ly/audiolibrary-playlists\n\n———\n\n❤️ Get in touch with Audio Library:\n\nE-mail: hello@audiolibrary.com.co\nWebsite: https://www.audiolibrary.com.co\nInstagram: http://bit.ly/aI-instagram\nFacebook: http://bit.ly/al-facebook\nSoundCloud: http://bit.ly/al-soundcloud\nTwitter: http://bit.ly/aI-twitter\n\n———\n\n🔥 Send your demo: http://www.audiolibrary.com.co/demo\n\n———\n\nPlease report to (report@audiolibrary.com.co) any issues with this video/song/image, from broken links, copyright claim/strikes to someone using the music without giving credit or selling the music.\n\n———\n\nRead our disclaimer before using the music.\nhttp://bit.ly/2KA71pn\n\n———\n\n#VlogMusic #NoCopyrightMusic #AudioLibrary",
        },
        defaultAudioLanguage: 'en',
      },
      contentDetails: {
        duration: 'PT3M11S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '31525',
        likeCount: '5023',
        favoriteCount: '0',
        commentCount: '58',
      },
      start: 99,
      end: 116,
    },
    {
      kind: 'youtube#video',
      etag: 'pd62X6-RPQ_6lf1ELzxLawSHfq0',
      id: 'Wlt9UaUBmf4',
      snippet: {
        publishedAt: '2022-01-17T12:00:13Z',
        channelId: 'UCht8qITGkBvXKsR1Byln-wA',
        title: 'Edelweiss – Onycs (No Copyright Music)',
        description:
          "Download free and safe music for content creators (Free Music, No Copyright Music, Royalty-free Music, and Creative Commons) · http://bit.ly/Join-the-family\n\nPlease subscribe! ❤️\nWe upload a new song EVERY day http://bit.ly/32TUZyy\n\n———\n\n⭐ Free Download: https://bit.ly/3092xB2\n\n———\n\n⚠️ You’re free to use this song in any of your YouTube videos, but you MUST include the following in your video description (Copy & Paste):\n\n––––––––––––––––––––––––––––––\nEdelweiss by Onycs https://soundcloud.com/onycsmusic\nCreative Commons — Attribution 3.0 Unported — CC BY 3.0 \nFree Download / Stream: https://bit.ly/3092xB2\nMusic promoted by Audio Library https://youtu.be/Wlt9UaUBmf4\n––––––––––––––––––––––––––––––\n\n🎵 Track Info:\n\nTitle: Edelweiss by Onycs\nGenre and Mood: Ambient + Calm\n\n———\n\n🎧 Available on: \n\nSpotify: https://spoti.fi/3oE2cjd\niTunes: https://apple.co/3pKb2v4\nDeezer: https://deezer.com/es/track/1560022822\nSoundCloud: https://soundcloud.com/onycsmusic/edelweiss\n\n———\n\n😊 Contact the Artist:\n\nOnycs:\nhttps://soundcloud.com/onycsmusic\nhttps://open.spotify.com/artist/0Xccb17GyXNiv7bCY18WvP\nhttps://music.apple.com/us/artist/onycs/1512965456\nhttps://youtube.com/channel/UCNQ6vKZ5ogEZ0tM2TvxLhQA\nhttps://deezer.com/us/artist/94433652\nhttps://twitter.com/Onycsmusic\nhttps://facebook.com/Onycsmusic\nhttps://paypal.me/EvrardVictor\n\n———\n\n✅ About using the music:\n\n- You MUST include the full credits in your video description.\n- You can NOT claim the music as your own.\n- You can NOT sell the music anywhere.\n- You can NOT use the music as background music for your own musical work without the artist's consent.\n- You can NOT use the music without giving any credits in the video description.\n- You can NOT remove or add parts from/to the credits.\n- You can NOT use third-party software to download the video/track, always use our download links\n- You MUST contact the artist if you wish to use the music on any kind of project outside of YouTube.\n\n⚠️ Important:\n\n- If you don't follow these policies, you can get a copyright claim/strike.\n- If you need more information about using music, please get in touch with the artist.\n- This channel is not an official YouTube channel.\n\n———\n\n💚 Listen to our Spotify playlists\n\nEDM: http://spoti.fi/30R0jTw\nLo-Fi: http://spoti.fi/38OptGM\nChill: http://spoti.fi/3rX5gWN\nHappy: https://spoti.fi/2Qjk6JD\n\n———\n\n🔴 Official Releases: http://bit.ly/al-plus\n\nWe have created a new channel where we do an agreement with the artist and our record label to make sure all the music is free and 100% safe. \n\n———\n\n🔀 More free music:\n\nPop Music: http://bit.ly/pop-music-playlist\nHip Hop & Rap Music: http://bit.ly/hip-hop-rap-playlist\nDance & Electronic Music: http://bit.ly/dance-electronic-playlist\n\nMore playlists: http://bit.ly/audiolibrary-playlists\n\n———\n\n❤️ Get in touch with Audio Library:\n\nE-mail: hello@audiolibrary.com.co\nWebsite: https://audiolibrary.com.co\nInstagram: http://bit.ly/aI-instagram\nFacebook: http://bit.ly/al-facebook\nSoundCloud: http://bit.ly/al-soundcloud\nTwitter: http://bit.ly/aI-twitter\n\n———\n\n🔥 Send your demo: http://audiolibrary.com.co/demo\n\n———\n\nPlease report to (report@audiolibrary.com.co) any issues with this video/song/image, from broken links, copyright claim/strikes to someone using the music without giving credit or selling the music.\n\n———\n\nRead our disclaimer before using the music.\nhttp://bit.ly/2KA71pn\n\n———\n\n#VlogMusic #NoCopyrightMusic #AudioLibrary",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/Wlt9UaUBmf4/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/Wlt9UaUBmf4/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/Wlt9UaUBmf4/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/Wlt9UaUBmf4/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/Wlt9UaUBmf4/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'Audio Library — Music for content creators',
        tags: [
          'Onycs',
          'Edelweiss',
          'Onycs - Edelweiss',
          'Onycs music',
          'audio library',
          'free music',
          'vlog',
          'vlog music',
          'no copyright music',
          'background music',
          'royalty free',
          'free music to use',
          'free music download',
          'free vlogging music',
          'free copyright music',
          'vlogger music',
          'vlogging music',
          'vlog no copyright',
          'music for vlog',
          'music for videos',
          'music for youtube videos',
          'download background music',
          'download free music',
          'download music',
          'ambient',
          'calm',
          'cc',
        ],
        categoryId: '10',
        liveBroadcastContent: 'none',
        defaultLanguage: 'en',
        localized: {
          title: 'Edelweiss – Onycs (No Copyright Music)',
          description:
            "Download free and safe music for content creators (Free Music, No Copyright Music, Royalty-free Music, and Creative Commons) · http://bit.ly/Join-the-family\n\nPlease subscribe! ❤️\nWe upload a new song EVERY day http://bit.ly/32TUZyy\n\n———\n\n⭐ Free Download: https://bit.ly/3092xB2\n\n———\n\n⚠️ You’re free to use this song in any of your YouTube videos, but you MUST include the following in your video description (Copy & Paste):\n\n––––––––––––––––––––––––––––––\nEdelweiss by Onycs https://soundcloud.com/onycsmusic\nCreative Commons — Attribution 3.0 Unported — CC BY 3.0 \nFree Download / Stream: https://bit.ly/3092xB2\nMusic promoted by Audio Library https://youtu.be/Wlt9UaUBmf4\n––––––––––––––––––––––––––––––\n\n🎵 Track Info:\n\nTitle: Edelweiss by Onycs\nGenre and Mood: Ambient + Calm\n\n———\n\n🎧 Available on: \n\nSpotify: https://spoti.fi/3oE2cjd\niTunes: https://apple.co/3pKb2v4\nDeezer: https://deezer.com/es/track/1560022822\nSoundCloud: https://soundcloud.com/onycsmusic/edelweiss\n\n———\n\n😊 Contact the Artist:\n\nOnycs:\nhttps://soundcloud.com/onycsmusic\nhttps://open.spotify.com/artist/0Xccb17GyXNiv7bCY18WvP\nhttps://music.apple.com/us/artist/onycs/1512965456\nhttps://youtube.com/channel/UCNQ6vKZ5ogEZ0tM2TvxLhQA\nhttps://deezer.com/us/artist/94433652\nhttps://twitter.com/Onycsmusic\nhttps://facebook.com/Onycsmusic\nhttps://paypal.me/EvrardVictor\n\n———\n\n✅ About using the music:\n\n- You MUST include the full credits in your video description.\n- You can NOT claim the music as your own.\n- You can NOT sell the music anywhere.\n- You can NOT use the music as background music for your own musical work without the artist's consent.\n- You can NOT use the music without giving any credits in the video description.\n- You can NOT remove or add parts from/to the credits.\n- You can NOT use third-party software to download the video/track, always use our download links\n- You MUST contact the artist if you wish to use the music on any kind of project outside of YouTube.\n\n⚠️ Important:\n\n- If you don't follow these policies, you can get a copyright claim/strike.\n- If you need more information about using music, please get in touch with the artist.\n- This channel is not an official YouTube channel.\n\n———\n\n💚 Listen to our Spotify playlists\n\nEDM: http://spoti.fi/30R0jTw\nLo-Fi: http://spoti.fi/38OptGM\nChill: http://spoti.fi/3rX5gWN\nHappy: https://spoti.fi/2Qjk6JD\n\n———\n\n🔴 Official Releases: http://bit.ly/al-plus\n\nWe have created a new channel where we do an agreement with the artist and our record label to make sure all the music is free and 100% safe. \n\n———\n\n🔀 More free music:\n\nPop Music: http://bit.ly/pop-music-playlist\nHip Hop & Rap Music: http://bit.ly/hip-hop-rap-playlist\nDance & Electronic Music: http://bit.ly/dance-electronic-playlist\n\nMore playlists: http://bit.ly/audiolibrary-playlists\n\n———\n\n❤️ Get in touch with Audio Library:\n\nE-mail: hello@audiolibrary.com.co\nWebsite: https://audiolibrary.com.co\nInstagram: http://bit.ly/aI-instagram\nFacebook: http://bit.ly/al-facebook\nSoundCloud: http://bit.ly/al-soundcloud\nTwitter: http://bit.ly/aI-twitter\n\n———\n\n🔥 Send your demo: http://audiolibrary.com.co/demo\n\n———\n\nPlease report to (report@audiolibrary.com.co) any issues with this video/song/image, from broken links, copyright claim/strikes to someone using the music without giving credit or selling the music.\n\n———\n\nRead our disclaimer before using the music.\nhttp://bit.ly/2KA71pn\n\n———\n\n#VlogMusic #NoCopyrightMusic #AudioLibrary",
        },
        defaultAudioLanguage: 'en',
      },
      contentDetails: {
        duration: 'PT4M9S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '2574',
        likeCount: '319',
        favoriteCount: '0',
        commentCount: '31',
      },
      start: 49,
      end: 109,
    },
    {
      kind: 'youtube#video',
      etag: '_Tbb9qCbnFDnPx9VyiUDyvM-Abk',
      id: 'M0TD7AGfnoU',
      snippet: {
        publishedAt: '2022-01-14T12:00:09Z',
        channelId: 'UCht8qITGkBvXKsR1Byln-wA',
        title: 'Dreamers – Nettson (No Copyright Music)',
        description:
          "Download free and safe music for content creators (Free Music, No Copyright Music, Royalty-free Music, and Creative Commons) · http://bit.ly/Join-the-family\n\nPlease subscribe! ❤️\nWe upload a new song EVERY day http://bit.ly/32TUZyy\n\n———\n\n⭐ Free Download: https://bit.ly/33ahNPl\n\n———\n\n⚠️ You’re free to use this song in any of your YouTube videos, but you MUST include the following in your video description (Copy & Paste):\n\n––––––––––––––––––––––––––––––\nDreamers by Nettson https://soundcloud.com/nettson\nCreative Commons — Attribution 3.0 Unported — CC BY 3.0\nFree Download / Stream: https://bit.ly/33ahNPl\nMusic promoted by Audio Library https://youtu.be/M0TD7AGfnoU\n––––––––––––––––––––––––––––––\n\n🎵 Track Info:\n\nTitle: Dreamers by Nettson\nGenre and Mood: Holiday + Calm\n\n———\n\n🎧 Available on: \n\nSpotify: https://spoti.fi/3y2XDlG\niTunes: https://apple.co/3oxgWR9\nDeezer: https://deezer.com/es/track/1358059152\nYouTube: https://youtube.com/watch?v=wk35qsE7Uhc\nSoundCloud: https://soundcloud.com/nettson/nettson-dreamers-official\nYouTube Music: https://music.youtube.com/watch?v=wk35qsE7Uhc\n\n———\n\n😊 Contact the Artist:\n\nNettson:\nhttps://soundcloud.com/nettson\nhttps://youtube.com/c/Nettson\nhttps://open.spotify.com/artist/5hI3ZAQ0H0pWWLFpWHdf4G\nhttps://music.apple.com/us/artist/nettson/1466867564\nhttps://instagram.com/nettsonsongs\n\n———\n\n✅ About using the music:\n\n- You MUST include the full credits in your video description.\n- You can NOT claim the music as your own.\n- You can NOT sell the music anywhere.\n- You can NOT use the music as background music for your own musical work without the artist's consent.\n- You can NOT use the music without giving any credits in the video description.\n- You can NOT remove or add parts from/to the credits.\n- You can NOT use third-party software to download the video/track, always use our download links\n- You MUST contact the artist if you wish to use the music on any kind of project outside of YouTube.\n\n⚠️ Important:\n\n- If you don't follow these policies, you can get a copyright claim/strike.\n- If you need more information about using music, please get in touch with the artist.\n- This channel is not an official YouTube channel.\n\n———\n\n💚 Listen to our Spotify playlists\n\nEDM: http://spoti.fi/30R0jTw\nLo-Fi: http://spoti.fi/38OptGM\nChill: http://spoti.fi/3rX5gWN\nHappy: https://spoti.fi/2Qjk6JD\n\n———\n\n🔴 Official Releases: http://bit.ly/al-plus\n\nWe have created a new channel where we do an agreement with the artist and our record label to make sure all the music is free and 100% safe. \n\n———\n\n🔀 More free music:\n\nPop Music: http://bit.ly/pop-music-playlist\nHip Hop & Rap Music: http://bit.ly/hip-hop-rap-playlist\nDance & Electronic Music: http://bit.ly/dance-electronic-playlist\n\nMore playlists: http://bit.ly/audiolibrary-playlists\n\n———\n\n❤️ Get in touch with Audio Library:\n\nE-mail: hello@audiolibrary.com.co\nWebsite: https://www.audiolibrary.com.co\nInstagram: http://bit.ly/aI-instagram\nFacebook: http://bit.ly/al-facebook\nSoundCloud: http://bit.ly/al-soundcloud\nTwitter: http://bit.ly/aI-twitter\n\n———\n\n🔥 Send your demo: http://www.audiolibrary.com.co/demo\n\n———\n\nPlease report to (report@audiolibrary.com.co) any issues with this video/song/image, from broken links, copyright claim/strikes to someone using the music without giving credit or selling the music.\n\n———\n\nRead our disclaimer before using the music.\nhttp://bit.ly/2KA71pn\n\n———\n\n#VlogMusic #NoCopyrightMusic #AudioLibrary",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/M0TD7AGfnoU/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/M0TD7AGfnoU/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/M0TD7AGfnoU/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/M0TD7AGfnoU/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/M0TD7AGfnoU/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'Audio Library — Music for content creators',
        tags: [
          'Markvard',
          'Dreamers',
          'Markvard - Dreamers',
          'Markvard music',
          'audio library',
          'free music',
          'vlog',
          'vlog music',
          'no copyright music',
          'background music',
          'royalty free',
          'free music to use',
          'free music download',
          'free vlogging music',
          'free copyright music',
          'vlogger music',
          'vlogging music',
          'vlog no copyright',
          'music for vlog',
          'music for videos',
          'music for youtube videos',
          'download background music',
          'download free music',
          'download music',
          'holiday',
          'calm',
          'cc',
        ],
        categoryId: '10',
        liveBroadcastContent: 'none',
        defaultLanguage: 'en',
        localized: {
          title: 'Dreamers – Nettson (No Copyright Music)',
          description:
            "Download free and safe music for content creators (Free Music, No Copyright Music, Royalty-free Music, and Creative Commons) · http://bit.ly/Join-the-family\n\nPlease subscribe! ❤️\nWe upload a new song EVERY day http://bit.ly/32TUZyy\n\n———\n\n⭐ Free Download: https://bit.ly/33ahNPl\n\n———\n\n⚠️ You’re free to use this song in any of your YouTube videos, but you MUST include the following in your video description (Copy & Paste):\n\n––––––––––––––––––––––––––––––\nDreamers by Nettson https://soundcloud.com/nettson\nCreative Commons — Attribution 3.0 Unported — CC BY 3.0\nFree Download / Stream: https://bit.ly/33ahNPl\nMusic promoted by Audio Library https://youtu.be/M0TD7AGfnoU\n––––––––––––––––––––––––––––––\n\n🎵 Track Info:\n\nTitle: Dreamers by Nettson\nGenre and Mood: Holiday + Calm\n\n———\n\n🎧 Available on: \n\nSpotify: https://spoti.fi/3y2XDlG\niTunes: https://apple.co/3oxgWR9\nDeezer: https://deezer.com/es/track/1358059152\nYouTube: https://youtube.com/watch?v=wk35qsE7Uhc\nSoundCloud: https://soundcloud.com/nettson/nettson-dreamers-official\nYouTube Music: https://music.youtube.com/watch?v=wk35qsE7Uhc\n\n———\n\n😊 Contact the Artist:\n\nNettson:\nhttps://soundcloud.com/nettson\nhttps://youtube.com/c/Nettson\nhttps://open.spotify.com/artist/5hI3ZAQ0H0pWWLFpWHdf4G\nhttps://music.apple.com/us/artist/nettson/1466867564\nhttps://instagram.com/nettsonsongs\n\n———\n\n✅ About using the music:\n\n- You MUST include the full credits in your video description.\n- You can NOT claim the music as your own.\n- You can NOT sell the music anywhere.\n- You can NOT use the music as background music for your own musical work without the artist's consent.\n- You can NOT use the music without giving any credits in the video description.\n- You can NOT remove or add parts from/to the credits.\n- You can NOT use third-party software to download the video/track, always use our download links\n- You MUST contact the artist if you wish to use the music on any kind of project outside of YouTube.\n\n⚠️ Important:\n\n- If you don't follow these policies, you can get a copyright claim/strike.\n- If you need more information about using music, please get in touch with the artist.\n- This channel is not an official YouTube channel.\n\n———\n\n💚 Listen to our Spotify playlists\n\nEDM: http://spoti.fi/30R0jTw\nLo-Fi: http://spoti.fi/38OptGM\nChill: http://spoti.fi/3rX5gWN\nHappy: https://spoti.fi/2Qjk6JD\n\n———\n\n🔴 Official Releases: http://bit.ly/al-plus\n\nWe have created a new channel where we do an agreement with the artist and our record label to make sure all the music is free and 100% safe. \n\n———\n\n🔀 More free music:\n\nPop Music: http://bit.ly/pop-music-playlist\nHip Hop & Rap Music: http://bit.ly/hip-hop-rap-playlist\nDance & Electronic Music: http://bit.ly/dance-electronic-playlist\n\nMore playlists: http://bit.ly/audiolibrary-playlists\n\n———\n\n❤️ Get in touch with Audio Library:\n\nE-mail: hello@audiolibrary.com.co\nWebsite: https://www.audiolibrary.com.co\nInstagram: http://bit.ly/aI-instagram\nFacebook: http://bit.ly/al-facebook\nSoundCloud: http://bit.ly/al-soundcloud\nTwitter: http://bit.ly/aI-twitter\n\n———\n\n🔥 Send your demo: http://www.audiolibrary.com.co/demo\n\n———\n\nPlease report to (report@audiolibrary.com.co) any issues with this video/song/image, from broken links, copyright claim/strikes to someone using the music without giving credit or selling the music.\n\n———\n\nRead our disclaimer before using the music.\nhttp://bit.ly/2KA71pn\n\n———\n\n#VlogMusic #NoCopyrightMusic #AudioLibrary",
        },
        defaultAudioLanguage: 'en',
      },
      contentDetails: {
        duration: 'PT3M33S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '30820',
        likeCount: '4932',
        favoriteCount: '0',
        commentCount: '47',
      },
      start: 98,
      end: 145,
    },
  ],
}
